name: Deploy TypeScript Azure Function

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: your-function-app-name # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project
  NODE_VERSION: "20.x" # set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: "Resolve Project Dependencies"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm run build
          popd

      - name: "Install Azure Functions Core Tools"
        run: |
          wget https://github.com/Azure/azure-functions-core-tools/releases/download/4.x/Azure.Functions.Cli.linux-x64.4.0.15.zip
          unzip Azure.Functions.Cli.linux-x64.4.0.15.zip
          sudo mv Azure.Functions.Cli /opt/azure-functions-cli
          sudo ln -s /opt/azure-functions-cli/func /usr/local/bin/func

      - name: "Prepare Function App Files"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --typescript
          popd

      - name: "Azure Login"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Optional: Add any additional Azure-specific deployment steps here

      - name: "Logout of Azure"
        run: |
          az logout
